// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbYbMkgCH0_SCSVy_CYXnC20DaQrLI-cs',
    appId: '1:81002314927:android:a60c734001a3e83f32e85a',
    messagingSenderId: '81002314927',
    projectId: 'gti-rides-01',
    storageBucket: 'gti-rides-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzah57m4q3za33YLd-leGH_lyZkUbVnaY',
    appId: '1:81002314927:ios:39f9643a17c8d64732e85a',
    messagingSenderId: '81002314927',
    projectId: 'gti-rides-01',
    storageBucket: 'gti-rides-01.appspot.com',
    androidClientId: '81002314927-4n20creg233t446hfgfeci4lt2ku92li.apps.googleusercontent.com',
    iosClientId: '81002314927-siqcjsfdr5imt7f5uncvlcon5ks35j4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtiRide',
  );
}
